stages:
  - test
  - report

unit_test_job:
  stage: test
  tags:
    - test
  script:
    - cd ./backend
    - mkdir -p src/main/resources/firebase
    - curl -o src/main/resources/firebase/moyeobang-d1dec-firebase-adminsdk-6uakm-bf0a8d2044.json https://moyeobang.s3.ap-southeast-2.amazonaws.com/moyeobang-d1dec-firebase-adminsdk-6uakm-bf0a8d2044.json
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - backend/build/test-results/test/
    reports:
      junit:
        - backend/build/test-results/test/**/*.xml
  only:
    - merge_requests
    - backend

result_report_job:
  stage: report
  tags:
    - test
  script:
    - ls -R backend/build/test-results/test/
    - |
      TEST_COUNT=$(grep -o "<testsuite" backend/build/test-results/test/*.xml | wc -l)
      FAIL_COUNT=$(grep -o "<failure" backend/build/test-results/test/*.xml | wc -l)
      SKIP_COUNT=$(grep -o "<skipped" backend/build/test-results/test/*.xml | wc -l)
      DURATION=$(grep -oP "(?<=time=\")[^\"]+" backend/build/test-results/test/**/*.xml | awk "{sum+=\$1} END {print sum}")

    - |
      curl --request POST --header "PRIVATE-TOKEN: AHt8jnrz-9FtsyyJPMt9" \
      --data-urlencode "body=## Unit Test Results\n- **$TEST_COUNT tests**, **$FAIL_COUNT failures**, **$SKIP_COUNT skipped**\n- ⏱️ Time taken: ${DURATION}s\nResults for commit [$CI_COMMIT_SHORT_SHA]($CI_PROJECT_URL/commit/$CI_COMMIT_SHA)\n\nThis comment has been updated with the latest results." \
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"
  
  dependencies:
    - unit_test_job

  only:
    - merge_requests
    - backend
