stages:
  - test

unit_test_job:
  stage: test

  tags:
    - test

  script:
    - cd ./backend
    - mkdir -p src/main/resources/firebase
    - curl -o src/main/resources/firebase/moyeobang-d1dec-firebase-adminsdk-6uakm-bf0a8d2044.json https://moyeobang.s3.ap-southeast-2.amazonaws.com/moyeobang-d1dec-firebase-adminsdk-6uakm-bf0a8d2044.json
    - ./gradlew test
    - |
      if compgen -G "build/test-results/test/**/*.xml" > /dev/null; then
        TEST_COUNT=$(grep -o "<testsuite" build/test-results/test/**/*.xml | wc -l)
        FAIL_COUNT=$(grep -o "<failure" build/test-results/test/**/*.xml | wc -l)
        SKIP_COUNT=$(grep -o "<skipped" build/test-results/test/**/*.xml | wc -l)
        DURATION=$(grep -oP "(?<=time=\")[^\"]+" build/test-results/test/**/*.xml | awk "{sum+=\$1} END {print sum}")
      else
        echo "No XML files found."
        TEST_COUNT=0
        FAIL_COUNT=0
        SKIP_COUNT=0
        DURATION=0
      fi
  
  after_script:
    - |
      curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --data-urlencode "body=## Unit Test Results\n- **$TEST_COUNT tests**, **$FAIL_COUNT failures**, **$SKIP_COUNT skipped**\n- ⏱️ Time taken: ${DURATION}s\nResults for commit [$CI_COMMIT_SHORT_SHA]($CI_PROJECT_URL/commit/$CI_COMMIT_SHA)\n\nThis comment has been updated with the latest results." \
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"

  artifacts:
    when: always
    paths:
      - backend/build/test-results/test/
    reports:
      junit:
        - backend/build/test-results/test/**/*.xml

  only:
    - merge_requests
    - backend
