stages:
  - test

unit_test_job:
  stage: test

  tags:
    - test

  script:
    - cd ./backend
    - ./gradlew test
    - 'TEST_COUNT=$(grep -o "<testsuite" build/test-results/test/**/*.xml | wc -l)'
    - 'FAIL_COUNT=$(grep -o "<failure" build/test-results/test/**/*.xml | wc -l)'
    - 'SKIP_COUNT=$(grep -o "<skipped" build/test-results/test/**/*.xml | wc -l)'
    - 'DURATION=$(grep -oP "(?<=time=\")[^\"]+" build/test-results/test/**/*.xml | awk "{sum+=\$1} END {print sum}")'
  
  after_script:
    - |
      curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --data-urlencode "body=## Unit Test Results\n- **$TEST_COUNT tests**, **$FAIL_COUNT failures**, **$SKIP_COUNT skipped**\n- ⏱️ Time taken: ${DURATION}s\nResults for commit [$CI_COMMIT_SHORT_SHA]($CI_PROJECT_URL/commit/$CI_COMMIT_SHA)\n\nThis comment has been updated with the latest results." \
      "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"

  artifacts:
    when: always
    paths:
      - backend/build/test-results/test/
    reports:
      junit:
        - backend/build/test-results/test/**/*.xml

  only:
    - merge_requests
    - backend
