spring:
  jwt:
    secret: rlagnsalsrhkmoyeobang
    issuer: moyeobang

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 88ff5247d4c3bb7864f3f05f06f2ca5b
            client-secret: 5CDGWICngwF8G3UhaPjPAx4GqJ0MPcJI
            redirect-uri: http://j11c102.p.ssafy.io:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
          google:
            client-name: google
            client-id: 843044088485-a42acvs9vsee2pqpn31p1olttsr8vonn.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://j11c102.p.ssafy.io:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
